### DISCUSSION TITLE
For anyone want to deploy this at home server...

### DISCUSSION THREAD

**Discussion by aidenlx** [spencerwooo/onedrive-vercel-index#112] [Show and tell]
check here for Dockerfile for this project: https://gist.github.com/aidenlx/882dae41f2dd8522c89c714df8fc113a

change configs in `config` folder and then put the file in the root dir of this project, then use `docker build -t onedrive-index .` to build image. 

When the image is built, it is possible to use the following to run `onedrive-vercel-index`

- `docker run -p 3000:3000 --restart always -e REFRESH_TOKEN=... -e CLIENT_SECRET=... -e ACCESS_TOKEN=... onedrive-index`
- with docker-compose: place the following `docker-compose.yml` file and then run `docker-compose up -d`

```yaml
version: "2.0"
services:
  onedrive-index:
    container_name: onedrive-index
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CLIENT_SECRET=...
      - REFRESH_TOKEN=...
      - ACCESS_TOKEN=...
    image: onedrive-index
```
