### ISSUE TITLE
关于夜间模式

### ISSUE THREAD

**Issue by aozaki-kuro** [spencerwooo/onedrive-vercel-index#63]
夜间模式部署了大概看了一下想提一下这些小问题：

## 文件列表颜色过于刺眼
![image](https://user-images.githubusercontent.com/28428951/130612217-a0dfb743-39f0-4b1b-b828-cb78ad67c206.png)

看了下目前的夜间模式，字体颜色是`255,255,255`，在大反差之下显得非常刺眼，尝试修改到`200,200,200`就已经非常柔和了，作为夜间模式至少不会晃眼。

```css
.dark\:text-white {
    --tw-text-opacity: 1;
    color: rgba(200,200,200,var(--tw-text-opacity));
}
```

但我没发现这个应该在哪里调……只能先开个issue了

## 白色横条？
![image](https://user-images.githubusercontent.com/28428951/130612440-9403ccaa-b4e1-4ddf-bda2-40b771c58803.png)

这个其实在最开始部署的就想问属于是bug还是feature了…目前夜间模式就这一条是非常突兀的灰色长条。不知道能不能干脆去掉。

## 文件列表栏和markdown preview的色差
![image](https://user-images.githubusercontent.com/28428951/130612680-8a710399-2ef3-4477-9997-118402fe5bfa.png)

目前上下色差挺明显的，下面的markdown preview配色似乎是跟着github主站的配色方案走了。想问下这是特意设计的差异吗？
